name: CI

# Trigger the workflow on push or pull request, but only for the
# master branch
on:
  pull_request:
  push:
    branches: [master]
    paths-ignore:
      - 'README.md'
      - 'stack.yaml'
      - '.travis.yml'

jobs:
  build:
    name: ghc ${{ matrix.versions.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - ghc: '8.2.2'
            cabal: '2.4'
          - ghc: '8.4.4'
            cabal: '2.4'
          - ghc: '8.6.5'
            cabal: '3.2'
          - ghc: '8.8.4'
            cabal: '3.2'
          - ghc: '8.10.1'
            cabal: '3.2'

    steps:
    - uses: actions/checkout@v2
      if: >-
        github.event.action == 'opened' ||
        github.event.action == 'synchronize' ||
        github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.versions.ghc }}
        cabal-version: ${{ matrix.versions.cabal }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.versions.ghc }}-cabal

    - name: Build
      run: |
        cabal v2-update
        cabal v2-build --enable-tests

    - name: Test
      run: |
        cabal v2-test --enable-tests
